#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")

. "${__type:?}/files/params.sh"

################################################################################
# Install dependencies

case ${os}
in
	(debian|devuan|ubuntu)
		# we require bzip2 to unpack the eXist DB dist tarball
		__package_apt bzip2
		exist_download_require='__package_apt/bzip2'

		# Java
		__package_apt default-jre
		;;
esac


################################################################################
# Download and unpack dist tarball

download_required=true  # FIXME

exist_dist_url="https://github.com/eXist-db/exist/releases/download/eXist-${version_selected:?}/exist-distribution-${version_selected:?}-unix.tar.bz2"

if ${download_required}
then
	__download "/tmp/${exist_dist_url##*/}" \
		--url "${exist_dist_url}" \
		--download remote \
		--sum "sha256:${sha256_should:?}"
	exist_download_require="${exist_download_require-}${exist_download_require:+ }__download/tmp/${exist_dist_url##*/}"

	require=${exist_download_require} \
	__unpack "/tmp/${exist_dist_url##*/}" \
		--destination "${exist_home:?}" \
		--sum-file "${exist_home:?}/.${exist_dist_url##*/}.cdist__unpack_sum" \
		--tar-strip 1 \
		--tar-extra-args ' -o'
	exist_download_require="${exist_download_require-}${exist_download_require:+ }__unpack/tmp/${exist_dist_url##*/}"
fi

################################################################################
# User

require=${exist_download_require-} \
__user "${exist_user:?}" \
	--system \
	--shell /sbin/nologin \
	--comment 'eXist-db service user' \
	--home "${exist_data_base:?}" \
	--create-home


################################################################################
# Create and patch directories

require="__user/${exist_user:?}" \
__directory "${exist_data}" \
	--owner "${exist_user:?}" --group "${exist_user:?}" --mode 0755

require="${exist_download_require-} __user/${exist_user:?} __directory/${exist_data}"
export require

# Fix up data/ link
__link "${exist_home:?}/data" \
	--type symbolic \
	--source "${exist_data:?}"

# Fix up logs/ link
require="__user/${exist_user:?}" \
__directory "/var/opt/log/exist/${version_selected:?}" \
	--owner "${exist_user:?}" --group "${exist_user:?}" --mode 0750 \
	--parents

__directory "${exist_home:?}/logs" \
	--state absent

require="__directory/${exist_home:?}/logs __directory/var/opt/log/exist/${version_selected:?}" \
__link "${exist_home:?}/logs" \
	--type symbolic \
	--source "/var/opt/log/exist/${version_selected:?}"


################################################################################
# Set up init scripts

case ${exist_init_type:?}
in
	(debian-sysvinit)
		# install the sysvinit scripts

		__file /etc/init.d/exist --state present \
			--owner 0 --group 0 --mode 0755 \
			--source "${__type:?}/files/init/debian/base.init"

		sed \
			-e "s#%%OPT_PACKAGE_NAME%%#${opt_package_name:?}#g" \
			-e "s/%%PACKAGE_VERSION%%/${version_selected:?}/g" \
			-e "s#%%EXIST_HOME%%#${exist_home:?}#g" \
			-e "s:%%EXIST_USER%%:${exist_user:?}:g" \
			<"${__type:?}/files/init/debian/exist5.init" \
			| __file "/etc/init.d/${opt_package_name:?}" --state present \
				  --owner 0 --group 0 --mode 0755 \
				  --source -

		exist_init_scripts="__file/etc/init.d/exist __file/etc/init.d/${opt_package_name:?}"

		# __file /etc/default/existdb
		# TODO: Set JAVA_HOME
		;;
	(systemd)
		__file /etc/systemd/system/exist-db.service --state present \
			--owner 0 --group 0 --mode 0755 \
			--source - <<-EOF
		$(sed \
			  -e "s/%%PACKAGE_VERSION%%/${version_selected:?}/g" \
			  -e "s#%%EXIST_HOME%%#${exist_home:?}#g" \
			..-e "s:%%EXIST_USER%%:${exist_user:?}:g" \
			..-e "s:%%EXIST_GROUP%%:${exist_user:?}:g" \
			..-e "s:%%EXIST_GROUP%%:${exist_user:?}:g" \
			<"${__type:?}/files/init/systemd/exist-db.service")
		EOF

		exist_init_scripts='__file/etc/systemd/system/exist-db.service'
		;;
esac
